### PR TITLE
ci(esp32): add build_idf522

### PR DESCRIPTION
**Pull request by lhdjply**
@kisvegabor  @liamHowatt     

https://github.com/lvgl/lvgl/pull/6241

Since I haven't used the ESP32 before, I can only modify it to this extent. I'm unsure how to resolve the remaining errors.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

The CI is failing here :slightly_frowning_face: 
https://github.com/lvgl/lv_micropython/actions/runs/10069665075/job/27836997145?pr=86#step:5:432

**Comment by lhdjply** [comment]
> Hi,
> 
> The CI is failing here 🙁 https://github.com/lvgl/lv_micropython/actions/runs/10069665075/job/27836997145?pr=86#step:5:432

I know, but I haven't used ESP32 before and I'm not sure how to resolve it 😕 It's just that I failed in https://github.com/lvgl/lvgl/pull/6241, I'm testing here first.

**Comment by liamHowatt** [comment]
```
/home/runner/work/lv_micropython/lv_micropython/lib/lv_bindings/driver/esp32/espidf.h:115:13: fatal error: esp32/clk.h: No such file or directory
  115 | #   include "esp32/clk.h"
      |             ^~~~~~~~~~~~~
```

Maybe that `#include` can be removed?
